// Code generated by Kitex v0.7.2. DO NOT EDIT.

package roomservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	room "github.com/li1553770945/sheepim-room-service/kitex_gen/room"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateRoom(ctx context.Context, callOptions ...callopt.Option) (r *room.CreateRoomResp, err error)
	JoinRoom(ctx context.Context, req *room.JoinRoomReq, callOptions ...callopt.Option) (r *room.JoinRoomResp, err error)
	GetRoomMembers(ctx context.Context, req *room.GetRoomMembersReq, callOptions ...callopt.Option) (r *room.GetRoomMembersResp, err error)
	CheckIsInRoom(ctx context.Context, req *room.CheckIsInRoomReq, callOptions ...callopt.Option) (r *room.CheckIsInRoomResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRoomServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRoomServiceClient struct {
	*kClient
}

func (p *kRoomServiceClient) CreateRoom(ctx context.Context, callOptions ...callopt.Option) (r *room.CreateRoomResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateRoom(ctx)
}

func (p *kRoomServiceClient) JoinRoom(ctx context.Context, req *room.JoinRoomReq, callOptions ...callopt.Option) (r *room.JoinRoomResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.JoinRoom(ctx, req)
}

func (p *kRoomServiceClient) GetRoomMembers(ctx context.Context, req *room.GetRoomMembersReq, callOptions ...callopt.Option) (r *room.GetRoomMembersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRoomMembers(ctx, req)
}

func (p *kRoomServiceClient) CheckIsInRoom(ctx context.Context, req *room.CheckIsInRoomReq, callOptions ...callopt.Option) (r *room.CheckIsInRoomResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckIsInRoom(ctx, req)
}
